package pojojo;
// Generated Oct 13, 2022 9:45:09 PM by Hibernate Tools 4.3.1

import java.util.List;
import javax.faces.bean.ManagedBean;
import Model.DAOInventory;


@ManagedBean
/**
 * TblBarang generated by hbm2java
 */
public class TblBarang  implements java.io.Serializable {


     private Integer barangId;
     private String barangName;
     private int stock;
     private int price;

    public TblBarang() {
    }

    public TblBarang(String barangName, int stock, int price) {
       this.barangName = barangName;
       this.stock = stock;
       this.price = price;
    }
   
    public Integer getBarangId() {
        return this.barangId;
    }
    
    public void setBarangId(Integer barangId) {
        this.barangId = barangId;
    }
    public String getBarangName() {
        return this.barangName;
    }
    
    public void setBarangName(String barangName) {
        this.barangName = barangName;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public List<TblBarang> getallrecords(){
        DAOInventory plg = new DAOInventory();
        List<TblBarang> lplg = plg.retrieveTblBarang();
        return lplg;
    }
    public List<TblBarang> getbyid(){
        DAOInventory adao = new DAOInventory();
        List<TblBarang> ldao = adao.getbyID1(barangId);
        barangName = ldao.get(0).barangName;
        stock = ldao.get(0).stock;
        price = ldao.get(0).price;

        return ldao;
    }
    public String update(){
        DAOInventory uadao =new DAOInventory();
        uadao.invUpdate(this);
        
        return "inventory";
    }
    public String addInven() {
        DAOInventory ctg = new DAOInventory();
        ctg.addInv(this);
        
        return "inventory";
    }
    public void delete()
    {    
        DAOInventory kdao = new DAOInventory();
        kdao.deleteInv(barangId);
    }

}


