package pojojo;
// Generated Oct 13, 2022 9:45:09 PM by Hibernate Tools 4.3.1

import Model.DAOEmploye;
import java.util.List;
import javax.faces.bean.ManagedBean;



@ManagedBean
/**
 * TblEmploye generated by hbm2java
 */
public class TblEmploye  implements java.io.Serializable {


     private Integer employeId;
     private String employeName;
     private String employeAddress;

    public TblEmploye() {
    }

    public TblEmploye(String employeName, String employeAddress) {
       this.employeName = employeName;
       this.employeAddress = employeAddress;
    }
   
    public Integer getEmployeId() {
        return this.employeId;
    }
    
    public void setEmployeId(Integer employeId) {
        this.employeId = employeId;
    }
    public String getEmployeName() {
        return this.employeName;
    }
    
    public void setEmployeName(String employeName) {
        this.employeName = employeName;
    }
    public String getEmployeAddress() {
        return this.employeAddress;
    }
    
    public void setEmployeAddress(String employeAddress) {
        this.employeAddress = employeAddress;
    }
    
    public List<TblEmploye> getallrecords(){
       DAOEmploye plg = new DAOEmploye();
        List<TblEmploye> lplg = plg.retrieveTblEmployes();
        return lplg;
    } 
    
    public List<TblEmploye> getbyid(){
        DAOEmploye adao = new DAOEmploye();
        List<TblEmploye> ldao = adao.getbyID1(employeId);
        employeName = ldao.get(0).employeName;
        employeAddress = ldao.get(0).employeAddress;
        
        return ldao;
    }
    
    public void update(){
        DAOEmploye uadao =new DAOEmploye();
        uadao.empUpdate(this);
        
        employeName = "";
        employeAddress = "";
    }
    
    public String addEmploye() {
        DAOEmploye ctg = new DAOEmploye();
        ctg.addEmply(this);
        employeName = "";
        employeAddress = "";
        return "employe";
    }
    
    public void delete()
    {    
        DAOEmploye kdao = new DAOEmploye();
        kdao.deleteEmply(employeId);
    }


}


