package pojojo;
// Generated Oct 13, 2022 9:45:09 PM by Hibernate Tools 4.3.1

import Model.DAOAdmin;
import Model.DAOLogin;
import java.util.List;
import javax.faces.bean.ManagedBean;


@ManagedBean

/**
 * TblUser generated by hbm2java
 */
public class TblUser  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;

    public TblUser() {
    }

    public TblUser(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    public String validasiLogin(){
        DAOLogin uDao = new DAOLogin();
        List<TblUser> us = uDao.getBy(username, password);
        try{
        if(us != null){
         username = us.get(0).username;
         password = us.get(0).password;
         return "dashboard";
        }
        }
        catch(Exception e){
        System.out.println("");
        }
        return "error";
    }
    
    public List<TblUser> getallrecords(){
        DAOAdmin plg = new DAOAdmin();
        List<TblUser> lplg = plg.retrieveTblAdmin();
        return lplg;
    } 
    
    public List<TblUser> getbyid(){
        DAOAdmin adao = new DAOAdmin();
        List<TblUser> ldao = adao.getbyID1(id);
        username = ldao.get(0).username;
        password = ldao.get(0).password;
        
        return ldao;
    }
    
    public void update(){
        DAOAdmin uadao = new DAOAdmin();
        uadao.adminUpdate(this);
        
        username = "";
    }
}


